cmake_minimum_required(VERSION 3.20)
file(MAKE_DIRECTORY "${LOG_DIR}")
set(flags -std=c++23 -DHAS_STD_LIB=1 -fsyntax-only)
foreach(directory IN LISTS INCLUDE_DIRS)
  if(NOT directory STREQUAL "")
    list(APPEND flags "-I${directory}")
  endif()
endforeach()
set(valid_cases 0 4)
set(invalid_cases 1 2 3 5 6 7)
foreach(case IN LISTS valid_cases invalid_cases)
  execute_process(COMMAND "${CXX}" ${flags} "-DPWM_CASE=${case}" "${CASE_SOURCE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
  file(WRITE "${LOG_DIR}/pwm-${case}.log" "${output}${errors}")
  if(case IN_LIST valid_cases)
    if(NOT result STREQUAL "0")
      message(FATAL_ERROR "Valid PWM case ${case} failed:\n${output}${errors}")
    endif()
  else()
    if(case EQUAL 3)
      set(diagnostic "Found resource conflict in same claim[.]")
    else()
      set(diagnostic "Application has resource conflict")
    endif()
    if(NOT result MATCHES "^[1-9][0-9]*$" OR
        NOT errors MATCHES "static assertion failed[^\n]*${diagnostic}")
      message(FATAL_ERROR "PWM case ${case}: expected resource diagnostic, got ${result}:\n${output}${errors}")
    endif()
  endif()
endforeach()
message(STATUS "PWM claim probes: 2 valid applications and 6 expected conflicts passed")
