cmake_minimum_required(VERSION 3.20)
file(MAKE_DIRECTORY "${LOG_DIR}")
if(COMPILER_ID STREQUAL "MSVC")
  set(flags /nologo /std:c++latest /Zc:__cplusplus /Zs /DHAS_STD_LIB=1)
  set(include_flag /I)
  set(define_flag /D)
else()
  set(flags -std=c++23 -DHAS_STD_LIB=1 -fsyntax-only)
  set(include_flag -I)
  set(define_flag -D)
endif()
foreach(directory IN LISTS INCLUDE_DIRS)
  if(NOT directory STREQUAL "")
    list(APPEND flags "${include_flag}${directory}")
  endif()
endforeach()
function(check_case kind id diagnostic)
  execute_process(COMMAND "${CXX}" ${flags} "${define_flag}CASE_ID=${id}"
    "${SOURCE_DIR}/${kind}_contract_probe.cpp"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
  file(WRITE "${LOG_DIR}/${kind}-${id}.log" "${output}${errors}")
  if(diagnostic STREQUAL "PASS")
    if(NOT result STREQUAL "0")
      message(FATAL_ERROR "${kind} positive case ${id} failed:\n${output}${errors}")
    endif()
  elseif(NOT result MATCHES "^[1-9][0-9]*$" OR
      NOT "${output}${errors}" MATCHES "(static assertion failed|static_assert failed)[^\n]*${diagnostic}")
    message(FATAL_ERROR "${kind} case ${id}: expected ${diagnostic}, got ${result}:\n${output}${errors}")
  endif()
endfunction()
foreach(id IN ITEMS 0 3 9)
  check_case(storage ${id} PASS)
endforeach()
foreach(id IN ITEMS 1 2 4 10)
  check_case(storage ${id} "Application has resource conflict")
endforeach()
check_case(storage 5 GREVIR_STORAGE_TYPE_NOT_TRIVIALLY_COPYABLE)
check_case(storage 6 GREVIR_STORAGE_NEGATIVE_ADDRESS)
check_case(storage 7 GREVIR_STORAGE_REGION_EXCEEDS_CAPACITY)
check_case(storage 8 GREVIR_STORAGE_CLAIM_RANGE_OVERFLOW)
message(STATUS "Storage probes: 3 valid regions/applications and 8 expected rejections passed")
check_case(timer 0 PASS)
check_case(timer 1 PASS)
check_case(timer 2 GREVIR_TIMER_ZERO_FREQUENCY_DIVIDER)
check_case(timer 3 GREVIR_TIMER_ZERO_FREQUENCY)
check_case(timer 4 GREVIR_TIMER_ZERO_RESOLUTION)
foreach(id IN ITEMS 5 6 7 10)
  check_case(timer ${id} GREVIR_TIMER_UNSATISFIED_CONFIG)
endforeach()
foreach(id IN ITEMS 8 9)
  check_case(timer ${id} GREVIR_TIMER_UNSUPPORTED_REQUIREMENT)
endforeach()
foreach(id IN ITEMS 11 12)
  check_case(timer ${id} GREVIR_TIMER_CONFLICTING_FREQUENCY_REQUESTS)
endforeach()
check_case(timer 13 GREVIR_TIMER_DUPLICATE_RESOLUTION_REQUESTS)
message(STATUS "Timer probes: 2 valid backend configurations and 12 expected rejections passed")
