include(CMakeFindDependencyMacro)
find_dependency(grevir-base CONFIG)
find_dependency(grevir-time CONFIG)
find_dependency(grevir-core CONFIG)
include("${CMAKE_CURRENT_LIST_DIR}/GrevirPeripheralsTargets.cmake")
